<?php
use Migrations\AbstractSeed;

/**
 * UserGroupPermissions seed.
 */
class UserGroupPermissionsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Pages',
                'action' => 'display',
                'allowed' => '1',
            ],
            [
                'id' => '2',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Pages',
                'action' => 'display',
                'allowed' => '1',
            ],
            [
                'id' => '3',
                'user_group_id' => '3',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Pages',
                'action' => 'display',
                'allowed' => '1',
            ],
            [
                'id' => '4',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Autocomplete',
                'action' => 'fetch',
                'allowed' => '1',
            ],
            [
                'id' => '5',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Autocomplete',
                'action' => 'fetch',
                'allowed' => '0',
            ],
            [
                'id' => '6',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'StaticPages',
                'action' => 'index',
                'allowed' => '1',
            ],
            [
                'id' => '7',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'StaticPages',
                'action' => 'add',
                'allowed' => '1',
            ],
            [
                'id' => '8',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'StaticPages',
                'action' => 'edit',
                'allowed' => '1',
            ],
            [
                'id' => '9',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'StaticPages',
                'action' => 'view',
                'allowed' => '1',
            ],
            [
                'id' => '10',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'StaticPages',
                'action' => 'delete',
                'allowed' => '1',
            ],
            [
                'id' => '11',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'StaticPages',
                'action' => 'preview',
                'allowed' => '1',
            ],
            [
                'id' => '12',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserContacts',
                'action' => 'index',
                'allowed' => '1',
            ],
            [
                'id' => '13',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserContacts',
                'action' => 'contactUs',
                'allowed' => '1',
            ],
            [
                'id' => '14',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserContacts',
                'action' => 'contactUs',
                'allowed' => '1',
            ],
            [
                'id' => '15',
                'user_group_id' => '3',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserContacts',
                'action' => 'contactUs',
                'allowed' => '1',
            ],
            [
                'id' => '16',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserContacts',
                'action' => 'sendReply',
                'allowed' => '1',
            ],
            [
                'id' => '17',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'StaticPages',
                'action' => 'preview',
                'allowed' => '1',
            ],
            [
                'id' => '18',
                'user_group_id' => '3',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'StaticPages',
                'action' => 'preview',
                'allowed' => '1',
            ],
            [
                'id' => '19',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserEmails',
                'action' => 'index',
                'allowed' => '1',
            ],
            [
                'id' => '20',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserEmails',
                'action' => 'send',
                'allowed' => '1',
            ],
            [
                'id' => '21',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserEmails',
                'action' => 'sendToUser',
                'allowed' => '1',
            ],
            [
                'id' => '22',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserEmails',
                'action' => 'view',
                'allowed' => '1',
            ],
            [
                'id' => '23',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserEmails',
                'action' => 'searchEmails',
                'allowed' => '1',
            ],
            [
                'id' => '24',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserEmailSignatures',
                'action' => 'index',
                'allowed' => '1',
            ],
            [
                'id' => '25',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserEmailSignatures',
                'action' => 'add',
                'allowed' => '1',
            ],
            [
                'id' => '26',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserEmailSignatures',
                'action' => 'edit',
                'allowed' => '1',
            ],
            [
                'id' => '27',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserEmailSignatures',
                'action' => 'delete',
                'allowed' => '1',
            ],
            [
                'id' => '28',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserEmailTemplates',
                'action' => 'index',
                'allowed' => '1',
            ],
            [
                'id' => '29',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserEmailTemplates',
                'action' => 'add',
                'allowed' => '1',
            ],
            [
                'id' => '30',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserEmailTemplates',
                'action' => 'edit',
                'allowed' => '1',
            ],
            [
                'id' => '31',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserEmailTemplates',
                'action' => 'delete',
                'allowed' => '1',
            ],
            [
                'id' => '32',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserGroupPermissions',
                'action' => 'permissionGroupMatrix',
                'allowed' => '1',
            ],
            [
                'id' => '33',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserGroupPermissions',
                'action' => 'permissionSubGroupMatrix',
                'allowed' => '1',
            ],
            [
                'id' => '34',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserGroupPermissions',
                'action' => 'changePermission',
                'allowed' => '1',
            ],
            [
                'id' => '35',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserGroupPermissions',
                'action' => 'getPermissions',
                'allowed' => '1',
            ],
            [
                'id' => '36',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserGroupPermissions',
                'action' => 'getPermissions',
                'allowed' => '0',
            ],
            [
                'id' => '37',
                'user_group_id' => '3',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserGroupPermissions',
                'action' => 'getPermissions',
                'allowed' => '0',
            ],
            [
                'id' => '38',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserGroups',
                'action' => 'index',
                'allowed' => '1',
            ],
            [
                'id' => '39',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserGroups',
                'action' => 'add',
                'allowed' => '1',
            ],
            [
                'id' => '40',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserGroups',
                'action' => 'edit',
                'allowed' => '1',
            ],
            [
                'id' => '41',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserGroups',
                'action' => 'delete',
                'allowed' => '1',
            ],
            [
                'id' => '42',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'dashboard',
                'allowed' => '1',
            ],
            [
                'id' => '43',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'dashboard',
                'allowed' => '1',
            ],
            [
                'id' => '44',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'index',
                'allowed' => '1',
            ],
            [
                'id' => '45',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'indexSearch',
                'allowed' => '1',
            ],
            [
                'id' => '46',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'online',
                'allowed' => '1',
            ],
            [
                'id' => '47',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'addUser',
                'allowed' => '1',
            ],
            [
                'id' => '48',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'editUser',
                'allowed' => '1',
            ],
            [
                'id' => '49',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'viewUser',
                'allowed' => '1',
            ],
            [
                'id' => '50',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'deleteUser',
                'allowed' => '1',
            ],
            [
                'id' => '51',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'setActive',
                'allowed' => '1',
            ],
            [
                'id' => '52',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'setInactive',
                'allowed' => '1',
            ],
            [
                'id' => '53',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'verifyEmail',
                'allowed' => '1',
            ],
            [
                'id' => '54',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'changeUserPassword',
                'allowed' => '1',
            ],
            [
                'id' => '55',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'logoutUser',
                'allowed' => '1',
            ],
            [
                'id' => '56',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'viewUserPermissions',
                'allowed' => '1',
            ],
            [
                'id' => '57',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'uploadCsv',
                'allowed' => '1',
            ],
            [
                'id' => '58',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'addMultipleUsers',
                'allowed' => '1',
            ],
            [
                'id' => '59',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'accessDenied',
                'allowed' => '1',
            ],
            [
                'id' => '60',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'accessDenied',
                'allowed' => '1',
            ],
            [
                'id' => '61',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'login',
                'allowed' => '1',
            ],
            [
                'id' => '62',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'login',
                'allowed' => '1',
            ],
            [
                'id' => '63',
                'user_group_id' => '3',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'login',
                'allowed' => '1',
            ],
            [
                'id' => '64',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'logout',
                'allowed' => '1',
            ],
            [
                'id' => '65',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'logout',
                'allowed' => '1',
            ],
            [
                'id' => '66',
                'user_group_id' => '3',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'logout',
                'allowed' => '1',
            ],
            [
                'id' => '67',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'register',
                'allowed' => '1',
            ],
            [
                'id' => '68',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'register',
                'allowed' => '0',
            ],
            [
                'id' => '69',
                'user_group_id' => '3',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'register',
                'allowed' => '1',
            ],
            [
                'id' => '70',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'myprofile',
                'allowed' => '1',
            ],
            [
                'id' => '71',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'myprofile',
                'allowed' => '1',
            ],
            [
                'id' => '72',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'editProfile',
                'allowed' => '1',
            ],
            [
                'id' => '73',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'editProfile',
                'allowed' => '1',
            ],
            [
                'id' => '74',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'changePassword',
                'allowed' => '1',
            ],
            [
                'id' => '75',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'changePassword',
                'allowed' => '1',
            ],
            [
                'id' => '76',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'deleteAccount',
                'allowed' => '1',
            ],
            [
                'id' => '77',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'deleteAccount',
                'allowed' => '0',
            ],
            [
                'id' => '78',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'forgotPassword',
                'allowed' => '1',
            ],
            [
                'id' => '79',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'forgotPassword',
                'allowed' => '1',
            ],
            [
                'id' => '80',
                'user_group_id' => '3',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'forgotPassword',
                'allowed' => '1',
            ],
            [
                'id' => '81',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'activatePassword',
                'allowed' => '1',
            ],
            [
                'id' => '82',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'activatePassword',
                'allowed' => '1',
            ],
            [
                'id' => '83',
                'user_group_id' => '3',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'activatePassword',
                'allowed' => '1',
            ],
            [
                'id' => '84',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'emailVerification',
                'allowed' => '1',
            ],
            [
                'id' => '85',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'emailVerification',
                'allowed' => '1',
            ],
            [
                'id' => '86',
                'user_group_id' => '3',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'emailVerification',
                'allowed' => '1',
            ],
            [
                'id' => '87',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'userVerification',
                'allowed' => '1',
            ],
            [
                'id' => '88',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'userVerification',
                'allowed' => '1',
            ],
            [
                'id' => '89',
                'user_group_id' => '3',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'userVerification',
                'allowed' => '1',
            ],
            [
                'id' => '90',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'Users',
                'action' => 'deleteCache',
                'allowed' => '1',
            ],
            [
                'id' => '91',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserSettings',
                'action' => 'index',
                'allowed' => '1',
            ],
            [
                'id' => '92',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserSettings',
                'action' => 'editSetting',
                'allowed' => '1',
            ],
            [
                'id' => '93',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserSettings',
                'action' => 'cakelog',
                'allowed' => '1',
            ],
            [
                'id' => '94',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserSettings',
                'action' => 'cakelogbackup',
                'allowed' => '1',
            ],
            [
                'id' => '95',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserSettings',
                'action' => 'cakelogdelete',
                'allowed' => '1',
            ],
            [
                'id' => '96',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserSettings',
                'action' => 'cakelogempty',
                'allowed' => '1',
            ],
            [
                'id' => '97',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'CronJobs',
                'action' => 'sendScheduledEmails',
                'allowed' => '1',
            ],
            [
                'id' => '98',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'ScheduledEmails',
                'action' => 'index',
                'allowed' => '1',
            ],
            [
                'id' => '99',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'ScheduledEmails',
                'action' => 'edit',
                'allowed' => '1',
            ],
            [
                'id' => '100',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'ScheduledEmails',
                'action' => 'view',
                'allowed' => '1',
            ],
            [
                'id' => '101',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'ScheduledEmails',
                'action' => 'delete',
                'allowed' => '1',
            ],
            [
                'id' => '102',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'ScheduledEmails',
                'action' => 'delete_recipient',
                'allowed' => '1',
            ],
            [
                'id' => '103',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'SettingOptions',
                'action' => 'index',
                'allowed' => '1',
            ],
            [
                'id' => '104',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'SettingOptions',
                'action' => 'add',
                'allowed' => '1',
            ],
            [
                'id' => '105',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'SettingOptions',
                'action' => 'edit',
                'allowed' => '1',
            ],
            [
                'id' => '106',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'SettingOptions',
                'action' => 'delete',
                'allowed' => '1',
            ],
            [
                'id' => '107',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => 'Usermgmt',
                'controller' => 'UserGroupPermissions',
                'action' => 'printPermissionChanges',
                'allowed' => '1',
            ],
            [
                'id' => '108',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'index',
                'allowed' => '0',
            ],
            [
                'id' => '109',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'allItems',
                'allowed' => '1',
            ],
            [
                'id' => '110',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'allItems',
                'allowed' => '1',
            ],
            [
                'id' => '111',
                'user_group_id' => '3',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'allItems',
                'allowed' => '0',
            ],
            [
                'id' => '112',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'allItemsCompany',
                'allowed' => '1',
            ],
            [
                'id' => '113',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'allItemsCompany',
                'allowed' => '1',
            ],
            [
                'id' => '114',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'allItemsRooms',
                'allowed' => '1',
            ],
            [
                'id' => '115',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'allItemsRooms',
                'allowed' => '1',
            ],
            [
                'id' => '116',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'allItemsRoom',
                'allowed' => '1',
            ],
            [
                'id' => '117',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'allItemsRoom',
                'allowed' => '1',
            ],
            [
                'id' => '118',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Rooms',
                'action' => 'addFront',
                'allowed' => '1',
            ],
            [
                'id' => '119',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Rooms',
                'action' => 'addFront',
                'allowed' => '1',
            ],
            [
                'id' => '120',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'addFront',
                'allowed' => '1',
            ],
            [
                'id' => '121',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'addFront',
                'allowed' => '1',
            ],
            [
                'id' => '122',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Users',
                'action' => 'add',
                'allowed' => '0',
            ],
            [
                'id' => '123',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Users',
                'action' => 'add',
                'allowed' => '0',
            ],
            [
                'id' => '124',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Users',
                'action' => 'addFront',
                'allowed' => '0',
            ],
            [
                'id' => '125',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Users',
                'action' => 'addFront',
                'allowed' => '0',
            ],
            [
                'id' => '126',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Collaborators',
                'action' => 'addFront',
                'allowed' => '1',
            ],
            [
                'id' => '127',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Collaborators',
                'action' => 'addFront',
                'allowed' => '1',
            ],
            [
                'id' => '128',
                'user_group_id' => '3',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Collaborators',
                'action' => 'getCollaboration',
                'allowed' => '1',
            ],
            [
                'id' => '129',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Collaborators',
                'action' => 'getCollaboration',
                'allowed' => '1',
            ],
            [
                'id' => '130',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Collaborators',
                'action' => 'startLogeed',
                'allowed' => '1',
            ],
            [
                'id' => '131',
                'user_group_id' => '3',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Users',
                'action' => 'register',
                'allowed' => '1',
            ],
            [
                'id' => '132',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Users',
                'action' => 'register',
                'allowed' => '1',
            ],
            [
                'id' => '133',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'getItem',
                'allowed' => '1',
            ],
            [
                'id' => '134',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'getItem',
                'allowed' => '1',
            ],
            [
                'id' => '135',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'item',
                'allowed' => '1',
            ],
            [
                'id' => '136',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'item',
                'allowed' => '1',
            ],
            [
                'id' => '137',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Comments',
                'action' => 'addFront',
                'allowed' => '1',
            ],
            [
                'id' => '138',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Comments',
                'action' => 'addFront',
                'allowed' => '1',
            ],
            [
                'id' => '139',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Files',
                'action' => 'addFiles',
                'allowed' => '1',
            ],
            [
                'id' => '140',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Files',
                'action' => 'addFiles',
                'allowed' => '1',
            ],
            [
                'id' => '141',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Files',
                'action' => 'download',
                'allowed' => '1',
            ],
            [
                'id' => '142',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Files',
                'action' => 'download',
                'allowed' => '1',
            ],
            [
                'id' => '143',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'editFront',
                'allowed' => '1',
            ],
            [
                'id' => '144',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'editFront',
                'allowed' => '1',
            ],
            [
                'id' => '145',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Comments',
                'action' => 'editFront',
                'allowed' => '1',
            ],
            [
                'id' => '146',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Comments',
                'action' => 'editFront',
                'allowed' => '1',
            ],
            [
                'id' => '147',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Files',
                'action' => 'deleteFile',
                'allowed' => '1',
            ],
            [
                'id' => '148',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Files',
                'action' => 'deleteFile',
                'allowed' => '1',
            ],
            [
                'id' => '149',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Files',
                'action' => 'deleteFront',
                'allowed' => '1',
            ],
            [
                'id' => '150',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Files',
                'action' => 'deleteFront',
                'allowed' => '1',
            ],
            [
                'id' => '151',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Comments',
                'action' => 'deleteFront',
                'allowed' => '1',
            ],
            [
                'id' => '152',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Comments',
                'action' => 'deleteFront',
                'allowed' => '1',
            ],
            [
                'id' => '153',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'deleteFront',
                'allowed' => '1',
            ],
            [
                'id' => '154',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Items',
                'action' => 'deleteFront',
                'allowed' => '1',
            ],
            [
                'id' => '155',
                'user_group_id' => '1',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Tests',
                'action' => 'index',
                'allowed' => '1',
            ],
            [
                'id' => '156',
                'user_group_id' => '2',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Tests',
                'action' => 'index',
                'allowed' => '1',
            ],
            [
                'id' => '157',
                'user_group_id' => '3',
                'prefix' => NULL,
                'plugin' => NULL,
                'controller' => 'Tests',
                'action' => 'index',
                'allowed' => '1',
            ],
        ];

        $table = $this->table('user_group_permissions');
        $table->insert($data)->save();
    }
}
