<?php
use Migrations\AbstractSeed;

/**
 * UserSettings seed.
 */
class UserSettingsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'name' => 'default_time_zone',
                'display_name' => 'Enter default time zone identifier for e.g. America/New_York',
                'value' => 'Atlantic/Canary',
                'type' => 'input',
                'category' => 'SITE',
            ],
            [
                'id' => '2',
                'name' => 'site_name',
                'display_name' => 'Enter Your Full Site Name',
                'value' => 'Comunicatec',
                'type' => 'input',
                'category' => 'SITE',
            ],
            [
                'id' => '3',
                'name' => 'site_name_short',
                'display_name' => 'Enter Your Short Site Name',
                'value' => 'Open Plan',
                'type' => 'input',
                'category' => 'SITE',
            ],
            [
                'id' => '4',
                'name' => 'login_redirect_url',
                'display_name' => 'Enter URL where user will be redirected after login',
                'value' => '/',
                'type' => 'input',
                'category' => 'SITE',
            ],
            [
                'id' => '5',
                'name' => 'logout_redirect_url',
                'display_name' => 'Enter URL where user will be redirected after logout',
                'value' => '/login',
                'type' => 'input',
                'category' => 'SITE',
            ],
            [
                'id' => '6',
                'name' => 'login_cookie_name',
                'display_name' => 'Please enter login cookie name for your site which is used to login user automatically for remember me functionality',
                'value' => 'UMPremiumCookie',
                'type' => 'input',
                'category' => 'SITE',
            ],
            [
                'id' => '7',
                'name' => 'use_https',
                'display_name' => 'Do you want to use HTTPS for whole site?',
                'value' => '0',
                'type' => 'checkbox',
                'category' => 'SITE',
            ],
            [
                'id' => '8',
                'name' => 'https_urls',
                'display_name' => 'You can enter selected urls for HTTPS, If URL belongs to any plugin then prepend plugin name in URL, if you want to allow all actions of controller on HTTPS then use controllername/* (e.g. usermgmt/users/login, usermgmt/users/register, products/cart, payments/*)',
                'value' => NULL,
                'type' => 'input',
                'category' => 'SITE',
            ],
            [
                'id' => '9',
                'name' => 'default_group_id',
                'display_name' => 'Enter default group id for user registration',
                'value' => '2',
                'type' => 'input',
                'category' => 'GROUP',
            ],
            [
                'id' => '10',
                'name' => 'admin_group_id',
                'display_name' => 'Enter Admin Group Id',
                'value' => '1',
                'type' => 'input',
                'category' => 'GROUP',
            ],
            [
                'id' => '11',
                'name' => 'guest_group_id',
                'display_name' => 'Enter Guest Group Id',
                'value' => '3',
                'type' => 'input',
                'category' => 'GROUP',
            ],
            [
                'id' => '12',
                'name' => 'site_registration',
                'display_name' => 'Do you want to allow new registrations?',
                'value' => '1',
                'type' => 'checkbox',
                'category' => 'USER',
            ],
            [
                'id' => '13',
                'name' => 'email_verification',
                'display_name' => 'Do you want user to verify his/her email address during registration?',
                'value' => '1',
                'type' => 'checkbox',
                'category' => 'EMAIL',
            ],
            [
                'id' => '14',
                'name' => 'allow_delete_account',
                'display_name' => 'Do you want to allow users to delete their account',
                'value' => '0',
                'type' => 'checkbox',
                'category' => 'USER',
            ],
            [
                'id' => '15',
                'name' => 'allow_change_username',
                'display_name' => 'Do you want to allow users to change their username?',
                'value' => '0',
                'type' => 'checkbox',
                'category' => 'USER',
            ],
            [
                'id' => '16',
                'name' => 'banned_usernames',
                'display_name' => 'Enter banned usernames comma separated(no space, no quotes)',
                'value' => 'Administrator, SuperAdmin',
                'type' => 'input',
                'category' => 'USER',
            ],
            [
                'id' => '17',
                'name' => 'permissions',
                'display_name' => 'Do you want to check permissions for users?',
                'value' => '1',
                'type' => 'checkbox',
                'category' => 'PERMISSION',
            ],
            [
                'id' => '18',
                'name' => 'admin_permissions',
                'display_name' => 'Do you want to check permissions for Admin?',
                'value' => '0',
                'type' => 'checkbox',
                'category' => 'PERMISSION',
            ],
            [
                'id' => '19',
                'name' => 'allow_user_multiple_login',
                'display_name' => 'Do you want to allow multiple logins with same user account for users(not admin)?',
                'value' => '1',
                'type' => 'checkbox',
                'category' => 'USER',
            ],
            [
                'id' => '20',
                'name' => 'allow_admin_multiple_login',
                'display_name' => 'Do you want to allow multiple logins with same user account for admin(not users)?',
                'value' => '1',
                'type' => 'checkbox',
                'category' => 'USER',
            ],
            [
                'id' => '21',
                'name' => 'login_idle_time',
                'display_name' => 'Set max idle time in minutes for user. This idle time will be used when multiple logins are not allowed for same user account. If max idle time reached since user last activity on the site then anyone can login with same account in other browser and idle user will be logged out.',
                'value' => '10',
                'type' => 'input',
                'category' => 'USER',
            ],
            [
                'id' => '22',
                'name' => 'view_online_user_time',
                'display_name' => 'You can view online users and guest from last few minutes, set time in minutes ',
                'value' => '30',
                'type' => 'input',
                'category' => 'USER',
            ],
            [
                'id' => '23',
                'name' => 'img_dir',
                'display_name' => 'Enter Image directory name where users profile photos will be uploaded. This directory should be in webroot/library directory',
                'value' => 'umphotos',
                'type' => 'input',
                'category' => 'USER',
            ],
            [
                'id' => '24',
                'name' => 'qrdn',
                'display_name' => 'Increase this number by 1 every time if you made any changes in CSS or JS file, If you delete cache from admin then it increases automatically',
                'value' => '123456792',
                'type' => 'input',
                'category' => 'SITE',
            ],
            [
                'id' => '25',
                'name' => 'use_remember_me',
                'display_name' => 'Do you want to show remember me feature on login page?',
                'value' => '1',
                'type' => 'checkbox',
                'category' => 'USER',
            ],
            [
                'id' => '26',
                'name' => 'email_from_address',
                'display_name' => 'Enter From Email Address to send emails',
                'value' => 'jefrey@conectatec.com',
                'type' => 'input',
                'category' => 'EMAIL',
            ],
            [
                'id' => '27',
                'name' => 'email_from_name',
                'display_name' => 'Enter From Email Name',
                'value' => 'Comunicatec',
                'type' => 'input',
                'category' => 'EMAIL',
            ],
            [
                'id' => '28',
                'name' => 'admin_email_address',
                'display_name' => 'Enter Admin Email Address to receive emails for e.g. contact enquiries',
                'value' => 'jefrey@conectatec.com',
                'type' => 'input',
                'category' => 'EMAIL',
            ],
            [
                'id' => '29',
                'name' => 'send_registration_mail',
                'display_name' => 'Do you want to send welcome registration email to user after registration',
                'value' => '0',
                'type' => 'checkbox',
                'category' => 'EMAIL',
            ],
            [
                'id' => '30',
                'name' => 'send_password_change_mail',
                'display_name' => 'Do you want to send password change email if users change their password',
                'value' => '0',
                'type' => 'checkbox',
                'category' => 'EMAIL',
            ],
            [
                'id' => '31',
                'name' => 'private_key_from_recaptcha',
                'display_name' => 'Enter private key for Recaptcha from google (also known as secret key)',
                'value' => NULL,
                'type' => 'input',
                'category' => 'RECAPTCHA',
            ],
            [
                'id' => '32',
                'name' => 'public_key_from_recaptcha',
                'display_name' => 'Enter public key for recaptcha from google (also known as site key)',
                'value' => NULL,
                'type' => 'input',
                'category' => 'RECAPTCHA',
            ],
            [
                'id' => '33',
                'name' => 'use_recaptcha_on_login',
                'display_name' => 'Do you want to add captcha support on login form?',
                'value' => '0',
                'type' => 'checkbox',
                'category' => 'RECAPTCHA',
            ],
            [
                'id' => '34',
                'name' => 'use_recaptcha_on_bad_login',
                'display_name' => 'Do you want to add captcha support on bad login? if user tried bad login credentials then after specifed bad login count recaptcha will be added on login form',
                'value' => '0',
                'type' => 'checkbox',
                'category' => 'RECAPTCHA',
            ],
            [
                'id' => '35',
                'name' => 'bad_login_allow_count',
                'display_name' => 'Enter bad login count to add captcha on login. for e.g. 5 or 10',
                'value' => '5',
                'type' => 'input',
                'category' => 'RECAPTCHA',
            ],
            [
                'id' => '36',
                'name' => 'use_recaptcha_on_registration',
                'display_name' => 'Do you want to add captcha support on registration form? ',
                'value' => '0',
                'type' => 'checkbox',
                'category' => 'RECAPTCHA',
            ],
            [
                'id' => '37',
                'name' => 'use_recaptcha_on_forgot_password',
                'display_name' => 'Do you want to add captcha support on forgot password page? ',
                'value' => '0',
                'type' => 'checkbox',
                'category' => 'RECAPTCHA',
            ],
            [
                'id' => '38',
                'name' => 'use_recaptcha_on_email_verification',
                'display_name' => 'Do you want to add captcha support on email verification page? ',
                'value' => '0',
                'type' => 'checkbox',
                'category' => 'RECAPTCHA',
            ],
            [
                'id' => '39',
                'name' => 'use_fb_login',
                'display_name' => 'Do you want to use Facebook Connect on your site?',
                'value' => '0',
                'type' => 'checkbox',
                'category' => 'FACEBOOK',
            ],
            [
                'id' => '40',
                'name' => 'fb_app_id',
                'display_name' => 'Enter Facebook Application Id',
                'value' => NULL,
                'type' => 'input',
                'category' => 'FACEBOOK',
            ],
            [
                'id' => '41',
                'name' => 'fb_secret',
                'display_name' => 'Enter Facebook Application Secret Code',
                'value' => NULL,
                'type' => 'input',
                'category' => 'FACEBOOK',
            ],
            [
                'id' => '42',
                'name' => 'fb_scope',
                'display_name' => 'Enter Facebook Permissions',
                'value' => 'email',
                'type' => 'input',
                'category' => 'FACEBOOK',
            ],
            [
                'id' => '43',
                'name' => 'use_twt_login',
                'display_name' => 'Want to use Twitter Connect on your site?',
                'value' => '0',
                'type' => 'checkbox',
                'category' => 'TWITTER',
            ],
            [
                'id' => '44',
                'name' => 'twt_app_id',
                'display_name' => 'Enter Twitter Consumer Key',
                'value' => NULL,
                'type' => 'input',
                'category' => 'TWITTER',
            ],
            [
                'id' => '45',
                'name' => 'twt_secret',
                'display_name' => 'Enter Twitter Consumer Secret',
                'value' => NULL,
                'type' => 'input',
                'category' => 'TWITTER',
            ],
            [
                'id' => '46',
                'name' => 'use_gmail_login',
                'display_name' => 'Do you want to use Google Connect on your site?',
                'value' => '0',
                'type' => 'checkbox',
                'category' => 'GOOGLE',
            ],
            [
                'id' => '47',
                'name' => 'gmail_api_key',
                'display_name' => 'Enter Google Api Key',
                'value' => NULL,
                'type' => 'input',
                'category' => 'GOOGLE',
            ],
            [
                'id' => '48',
                'name' => 'gmail_client_id',
                'display_name' => 'Enter Google Client Id',
                'value' => NULL,
                'type' => 'input',
                'category' => 'GOOGLE',
            ],
            [
                'id' => '49',
                'name' => 'gmail_client_secret',
                'display_name' => 'Enter Google Client Secret',
                'value' => NULL,
                'type' => 'input',
                'category' => 'GOOGLE',
            ],
            [
                'id' => '50',
                'name' => 'use_yahoo_login',
                'display_name' => 'Do you want to use Yahoo Connect on your site?',
                'value' => '0',
                'type' => 'checkbox',
                'category' => 'YAHOO',
            ],
            [
                'id' => '51',
                'name' => 'use_ldn_login',
                'display_name' => 'Do you want to use Linkedin Connect on your site?',
                'value' => '0',
                'type' => 'checkbox',
                'category' => 'LINKEDIN',
            ],
            [
                'id' => '52',
                'name' => 'ldn_api_key',
                'display_name' => 'Enter Linkedin Api Key',
                'value' => NULL,
                'type' => 'input',
                'category' => 'LINKEDIN',
            ],
            [
                'id' => '53',
                'name' => 'ldn_secret_key',
                'display_name' => 'Enter Linkedin Secret Key',
                'value' => NULL,
                'type' => 'input',
                'category' => 'LINKEDIN',
            ],
            [
                'id' => '54',
                'name' => 'use_fs_login',
                'display_name' => 'Do you want to use Foursquare Connect on your site?',
                'value' => '0',
                'type' => 'checkbox',
                'category' => 'FOURSQUARE',
            ],
            [
                'id' => '55',
                'name' => 'fs_client_id',
                'display_name' => 'Enter Foursquare Client Id',
                'value' => NULL,
                'type' => 'input',
                'category' => 'FOURSQUARE',
            ],
            [
                'id' => '56',
                'name' => 'fs_client_secret',
                'display_name' => 'Enter Foursquare Client Secret',
                'value' => NULL,
                'type' => 'input',
                'category' => 'FOURSQUARE',
            ],
            [
                'id' => '57',
                'name' => 'change_password_on_social_registration',
                'display_name' => 'Do you want to show change password page after user registration from social account?',
                'value' => '1',
                'type' => 'checkbox',
                'category' => 'USER',
            ],
            [
                'id' => '58',
                'name' => 'default_html_editor',
                'display_name' => 'Which is default html editor for your application, possible values are Tinymce, Ckeditor',
                'value' => '2',
                'type' => 'radio',
                'category' => 'SITE',
            ],
            [
                'id' => '59',
                'name' => 'notification_message_position',
                'display_name' => 'We are using toastr message notification. Please enter flash message position on screen. possible values are
toast-top-center
toast-bottom-center
toast-top-full-width
toast-bottom-full-width
toast-top-left
toast-top-right
toast-bottom-right
toast-bottom-left',
                'value' => 'toast-top-full-width',
                'type' => 'input',
                'category' => 'SITE',
            ],
            [
                'id' => '60',
                'name' => 'notification_message_close_time',
                'display_name' => 'We are using toastr message notification. Please enter flash message close/hide time in seconds. You can leave blank if you do not want to auto close/hide.',
                'value' => '10',
                'type' => 'input',
                'category' => 'SITE',
            ],
        ];

        $table = $this->table('user_settings');
        $table->insert($data)->save();
    }
}
